services:
  postgres:
    image: postgres:14.5-alpine
    container_name: s3-sync-postgres
    environment:
      POSTGRES_DB: s3sync
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  localstack:
    image: localstack/localstack:3.4
    container_name: s3-sync-localstack
    environment:
      SERVICES: s3
      DEBUG: "1"
      AWS_DEFAULT_REGION: eu-central-1
    ports:
      - "4566:4566"
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./.localstack}:/var/lib/localstack"

volumes:
  postgres-data:
